title: Aaron Gember-Jacobson
description: >- # this means to ignore newlines until "baseurl:"
    Associate Professor of Computer Science, Colgate University

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aaron.gember-jacobson.com" # the base hostname & protocol for your site, e.g. http://example.com

#plugins:
#  - jekyll-seo-tag
#  - jekyll-scholar

# collections
collections:
  pages:
    output: true
    permalink: /:title/

# excluded files
exclude: [readme.md, Gemfile, Gemfile.lock]
